"""empty message

Revision ID: b65f10f38e51
Revises: 4f4eecffaa2d
Create Date: 2022-05-03 16:21:38.228294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b65f10f38e51'
down_revision = '4f4eecffaa2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('hair_color', sa.String(length=60), nullable=True))
    op.add_column('characters', sa.Column('eye_color', sa.String(length=60), nullable=True))
    op.add_column('characters', sa.Column('planet', sa.String(length=60), nullable=True))
    op.alter_column('characters', 'character_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('character_name', table_name='characters')
    op.drop_index('character_name_2', table_name='characters')
    op.create_unique_constraint(None, 'characters', ['id'])
    op.create_unique_constraint(None, 'people', ['id'])
    op.add_column('planets', sa.Column('climate', sa.Integer(), nullable=True))
    op.add_column('planets', sa.Column('gravity', sa.Integer(), nullable=True))
    op.add_column('planets', sa.Column('population', sa.Integer(), nullable=True))
    op.alter_column('planets', 'planet_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('planet_name', table_name='planets')
    op.drop_index('planet_name_2', table_name='planets')
    op.create_unique_constraint(None, 'planets', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.create_index('planet_name_2', 'planets', ['planet_name'], unique=False)
    op.create_index('planet_name', 'planets', ['planet_name'], unique=False)
    op.alter_column('planets', 'planet_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'gravity')
    op.drop_column('planets', 'climate')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'characters', type_='unique')
    op.create_index('character_name_2', 'characters', ['character_name'], unique=False)
    op.create_index('character_name', 'characters', ['character_name'], unique=False)
    op.alter_column('characters', 'character_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('characters', 'planet')
    op.drop_column('characters', 'eye_color')
    op.drop_column('characters', 'hair_color')
    op.drop_column('characters', 'age')
    op.drop_column('characters', 'height')
    # ### end Alembic commands ###
